[package]
name = "sleep-on-lan"
version = "0.5.0"
edition = "2024"
rust-version = "1.96"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.34"
env_logger = "0.11.11"
systemd-journal-logger = "2.2.2"

mac_address = "1.1.8"
clap = "4.6.6"
configparser = "3.2.0"
