[package]
name = "sleep-on-lan"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.22"
env_logger = "0.11.5"
mac_address = "1.1.8"
clap = "4.5.18"
configparser = "3.1.0"
