[package]
name = "sleep-on-lan"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
env_logger = "0.10.2"
mac_address = "1.1.5"
clap = "4.4.18"
configparser = "3.0.4"
