---
name: "Build project"

on:
  pull_request:
  push:
    branches: ["master"]
  # allow to trigger workflow manually
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"

      - name: "Build"
        run: "make build"

      - name: "Run tests"
        run: "make test"
...
